/*
  Racing Suits Layout Adjustment Config

  EDIT THIS FILE to tune positions and scale.
  Each screen section only affects that one screen.

  FIELD GUIDE (what to edit):
  - x: move element left/right (number = px)
  - y: move element up/down (number = px)
  - padding: all inner spacing sides
  - paddingX / paddingY: left-right / top-bottom spacing
  - paddingTop / Right / Bottom / Left: one side only
  - scale: uniform size (1 = normal)
  - scaleX / scaleY: width-only or height-only scale
  - sizeX / sizeY: width and height
  - positionX / positionY: CSS left/top offsets
  - origin: transform pivot (example: "center center")

  VALUE RULES:
  - number: 12 -> 12px
  - string with unit: "50%", "2rem", "10vw"
  - empty string "": no override (use normal CSS)
*/

export const LAYOUT_ADJUSTMENTS_CONFIG = {
  // SECTION: Global (global)
  // Edit values below to adjust elements on this screen only.
  "global": {
    // HTML Root (:root)
    ":root": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Body Container (:body)
    ":body": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // App Container (:app)
    ":app": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // App Header (.app-header)
    ".app-header": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Player Profile (.player-profile)
    ".player-profile": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Player Avatar (.player-avatar)
    ".player-avatar": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Player Meta (.player-meta)
    ".player-meta": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Player Kicker (.player-kicker)
    ".player-kicker": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Tagline (.tagline)
    ".tagline": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Player Stats (.player-stats)
    ".player-stats": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Chip Count (#chip-count)
    "#chip-count": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Floating Nav (#floating-nav)
    "#floating-nav": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Floating Menu Btn (#floating-menu-btn)
    "#floating-menu-btn": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Screen Transition Streak (#screen-transition-streak)
    "#screen-transition-streak": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    }
  },
  // SECTION: Banner Screen (screen-banner)
  // Edit values below to adjust elements on this screen only.
  "screen-banner": {
    // Screen Container (:screen)
    ":screen": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Banner Image (.banner-image)
    ".banner-image": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    }
  },
  // SECTION: Selection Screen (screen-suit)
  // Edit values below to adjust elements on this screen only.
  "screen-suit": {
    // Screen Container (:screen)
    ":screen": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Suit Title (#suit-title)
    "#suit-title": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Suit Options (#suit-options)
    "#suit-options": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Suit Option (.suit-option)
    ".suit-option": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Suit Racer Image (.suit-racer-image)
    ".suit-racer-image": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Suit Confirm Btn (#suit-confirm-btn)
    "#suit-confirm-btn": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    }
  },
  // SECTION: Ante Screen (screen-ante)
  // Edit values below to adjust elements on this screen only.
  "screen-ante": {
    // Screen Container (:screen)
    ":screen": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Ante Title (#ante-title)
    "#ante-title": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Ante Panel (.ante-panel)
    ".ante-panel": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Ante Summary (.ante-summary)
    ".ante-summary": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Available Chip Count (#available-chip-count)
    "#available-chip-count": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Ante Slider Wrap (.ante-slider-wrap)
    ".ante-slider-wrap": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Ante Slider (#ante-slider)
    "#ante-slider": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Ante Slider Labels (.ante-slider-labels)
    ".ante-slider-labels": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Ante Min Label (#ante-min-label)
    "#ante-min-label": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Ante Max Label (#ante-max-label)
    "#ante-max-label": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Ante Value (.ante-value)
    ".ante-value": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Ante Value (#ante-value)
    "#ante-value": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Ante Racer Stage (.ante-racer-stage)
    ".ante-racer-stage": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Ante Racer Image (#ante-racer-image)
    "#ante-racer-image": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Ante Actions (.ante-actions)
    ".ante-actions": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Ante Back Btn (#ante-back-btn)
    "#ante-back-btn": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Ante Confirm Btn (#ante-confirm-btn)
    "#ante-confirm-btn": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    }
  },
  // SECTION: Menu Screen (screen-menu)
  // Edit values below to adjust elements on this screen only.
  "screen-menu": {
    // Screen Container (:screen)
    ":screen": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Menu Title (#menu-title)
    "#menu-title": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Menu Panel (.menu-panel)
    ".menu-panel": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Menu Home Btn (#menu-home-btn)
    "#menu-home-btn": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Menu Leaderboard Btn (#menu-leaderboard-btn)
    "#menu-leaderboard-btn": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Menu Settings Btn (#menu-settings-btn)
    "#menu-settings-btn": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Menu Bsg Btn (#menu-bsg-btn)
    "#menu-bsg-btn": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Menu Store Btn (#menu-store-btn)
    "#menu-store-btn": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Menu Back Btn (#menu-back-btn)
    "#menu-back-btn": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    }
  },
  // SECTION: Stats Screen (screen-stats)
  // Edit values below to adjust elements on this screen only.
  "screen-stats": {
    // Screen Container (:screen)
    ":screen": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Stats Title (#stats-title)
    "#stats-title": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Stats Page Tabs (.stats-page-tabs)
    ".stats-page-tabs": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Stats Page Btn (.stats-page-btn)
    ".stats-page-btn": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Stats Page Wins Btn (#stats-page-wins-btn)
    "#stats-page-wins-btn": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Stats Page Streak Btn (#stats-page-streak-btn)
    "#stats-page-streak-btn": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Stats Page Chips Btn (#stats-page-chips-btn)
    "#stats-page-chips-btn": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Stats Leaderboards (.stats-leaderboards)
    ".stats-leaderboards": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Stats Board (.stats-board)
    ".stats-board": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Leaderboard Page (.leaderboard-page)
    ".leaderboard-page": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Medal Strip (.medal-strip)
    ".medal-strip": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Leaderboard Main Value (.leaderboard-main-value)
    ".leaderboard-main-value": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Player Position Note (.player-position-note)
    ".player-position-note": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Wins Board Page (#wins-board-page)
    "#wins-board-page": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Streak Board Page (#streak-board-page)
    "#streak-board-page": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Chips Board Page (#chips-board-page)
    "#chips-board-page": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Wins Main Value (#wins-main-value)
    "#wins-main-value": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Streak Main Value (#streak-main-value)
    "#streak-main-value": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Chips Main Value (#chips-main-value)
    "#chips-main-value": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Wins Player Position (#wins-player-position)
    "#wins-player-position": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Streak Player Position (#streak-player-position)
    "#streak-player-position": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Chips Player Position (#chips-player-position)
    "#chips-player-position": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Stats Menu Btn (#stats-menu-btn)
    "#stats-menu-btn": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Stats Selection Btn (#stats-selection-btn)
    "#stats-selection-btn": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    }
  },
  // SECTION: BSG Screen (screen-bsg)
  // Edit values below to adjust elements on this screen only.
  "screen-bsg": {
    // Screen Container (:screen)
    ":screen": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Bsg Title (#bsg-title)
    "#bsg-title": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Info Panel (.info-panel)
    ".info-panel": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Bsg Menu Btn (#bsg-menu-btn)
    "#bsg-menu-btn": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    }
  },
  // SECTION: Store Screen (screen-store)
  // Edit values below to adjust elements on this screen only.
  "screen-store": {
    // Screen Container (:screen)
    ":screen": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Store Title (#store-title)
    "#store-title": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Info Panel (.info-panel)
    ".info-panel": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Store Menu Btn (#store-menu-btn)
    "#store-menu-btn": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    }
  },
  // SECTION: Settings Screen (screen-settings)
  // Edit values below to adjust elements on this screen only.
  "screen-settings": {
    // Screen Container (:screen)
    ":screen": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Settings Title (#settings-title)
    "#settings-title": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Settings Panel (.settings-panel)
    ".settings-panel": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Settings Row (.settings-row)
    ".settings-row": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Settings Sound Toggle (#settings-sound-toggle)
    "#settings-sound-toggle": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Settings Music Toggle (#settings-music-toggle)
    "#settings-music-toggle": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Settings Instant Win Toggle (#settings-instant-win-toggle)
    "#settings-instant-win-toggle": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Settings Menu Btn (#settings-menu-btn)
    "#settings-menu-btn": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    }
  },
  // SECTION: Race Screen (screen-race)
  // Edit values below to adjust elements on this screen only.
  "screen-race": {
    // Screen Container (:screen)
    ":screen": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Race Title (#race-title)
    "#race-title": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Race Layout (.race-layout)
    ".race-layout": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Track Board (.track-board)
    ".track-board": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Track Viewport (.track-viewport)
    ".track-viewport": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Race Grid (#race-grid)
    "#race-grid": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Track Row (.track-row)
    ".track-row": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Track Row Finish Row (.track-row.finish-row)
    ".track-row.finish-row": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Track Row Start Row (.track-row.start-row)
    ".track-row.start-row": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Track Cell (.track-cell)
    ".track-cell": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Track Cell Lane Cell (.track-cell.lane-cell)
    ".track-cell.lane-cell": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Track Cell Side Card Cell (.track-cell.side-card-cell)
    ".track-cell.side-card-cell": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Side Card Image (.side-card-image)
    ".side-card-image": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Race Marker Layer (.race-marker-layer)
    ".race-marker-layer": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Lane Racer Marker (.lane-racer-marker)
    ".lane-racer-marker": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Lane Racer Icon (.lane-racer-icon)
    ".lane-racer-icon": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Race Sidebar (.race-sidebar)
    ".race-sidebar": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Race Rankings (#race-rankings)
    "#race-rankings": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Leaderboard Entry (.leaderboard-entry)
    ".leaderboard-entry": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Leaderboard Racer (.leaderboard-racer)
    ".leaderboard-racer": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Draw Area (.draw-area)
    ".draw-area": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Current Draw Card (#current-draw-card)
    "#current-draw-card": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Draw Card (.draw-card)
    ".draw-card": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Draw Card Image (.draw-card-image)
    ".draw-card-image": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Draw Card Back (.draw-card-back)
    ".draw-card-back": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Race Start Sequence (.race-start-sequence)
    ".race-start-sequence": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Start Lights (.start-lights)
    ".start-lights": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Start Light (.start-light)
    ".start-light": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Start Go (.start-go)
    ".start-go": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    }
  },
  // SECTION: Result Screen (screen-result)
  // Edit values below to adjust elements on this screen only.
  "screen-result": {
    // Screen Container (:screen)
    ":screen": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Result Title (#result-title)
    "#result-title": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Result Banner (#result-banner)
    "#result-banner": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Result Showcase (#result-showcase)
    "#result-showcase": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Result Showcase (.result-showcase)
    ".result-showcase": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Result Crowd (#result-crowd)
    "#result-crowd": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Result Confetti (#result-confetti)
    "#result-confetti": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Winner Medal (.winner-medal)
    ".winner-medal": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Result Trophy (.result-trophy)
    ".result-trophy": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Result Winner Image (#result-winner-image)
    "#result-winner-image": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Result Copy (#result-copy)
    "#result-copy": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    },
    // Race Again Btn (#race-again-btn)
    "#race-again-btn": {
      x: 0,
      y: 0,
      padding: "",
      paddingX: "",
      paddingY: "",
      paddingTop: "",
      paddingRight: "",
      paddingBottom: "",
      paddingLeft: "",
      scale: 1,
      scaleX: "",
      scaleY: "",
      sizeX: "",
      sizeY: "",
      positionX: "",
      positionY: "",
      origin: ""
    }
  }
};
